<a href="https://colab.research.google.com/github/newyan/LearnAI/blob/main/AI_learn_phase0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np
import pandas as pd

print("Python:", sys.version.split()[0])
print("NumPy:", np.__version__)
print("pandas:", pd.__version__)

Python: 3.13.16
NumPy: 2.1.3
pandas: 2.2.3


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print("doubled:", a * 2)
print("mean:", a.mean())

[1 2 3 4 5]
doubled: [ 2  4  6  8 10]
mean: 3.0


In [ ]:
import numpy as np

a = np.arange(1, 10+1) ** 2
print(a)
print("sum:", a.sum())

[  1   4   9  16  25  36  49  64  81 100]
sum: 385


In [ ]:
import numpy as np
# 1. Make a 3x4 array with the numbers 1..12 (hint: np.arange + .reshape)
# 2. Print its shape
# 3. Print the second row (hint: indexing starts at 0)
# 4. Print the mean of each column (hint: .mean(axis=...))

array = np.arange(1, 13).reshape(3, 4)
print(array.shape)
print(array[1])
np.mean(array, 0)

(3, 4)
[5 6 7 8]


array([5., 6., 7., 8.])

In [ ]:
import pandas as pd
# 1. Build a DataFrame with columns name, age, score:
#    Alice 25 88, Bob 30 92, Carol 22 75
# 2. Print just the score column
# 3. Print only the rows where score is above 80

data = {
    "name" : ["Alice", "Bob", "Carol"],
    "age" : [25, 30, 22],
    "score" : [88, 92, 75]
}
df = pd.DataFrame(data)

print(df["score"])
print(df[df['score'] > 80])



0    88
1    92
2    75
Name: score, dtype: int64
    name  age  score
0  Alice   25     88
1    Bob   30     92


In [ ]:
# 1. Add a new column "passed" that is True where score >= 80, False otherwise
#    (hint: it's just the comparison from task 3, assigned to a new column)
# 2. Print only the names of the people who passed
#    (hint: filter the rows, then select the column — combine both skills)

import pandas as pd

data = {
    "name" : ["Alice", "Bob", "Carol"],
    "age" : [25, 30, 22],
    "score" : [88, 92, 75]
}
df = pd.DataFrame(data)

df["passed"] = df["score"] >= 80
print(df['name'][df["passed"]])


0    Alice
1      Bob
Name: name, dtype: object


In [23]:
# 1. Print summary stats for the numeric columns (hint: .describe())
# 2. Print the DataFrame sorted by score, highest first (hint: .sort_values)
# 3. What is the average age of the people who passed?
#    (combine today's skills: filter the rows, select the column, take the mean)

import pandas as pd

data = {
    "name" : ["Alice", "Bob", "Carol"],
    "age" : [25, 30, 22],
    "score" : [88, 92, 75]
}
df = pd.DataFrame(data)

df["passed"] = df["score"] >= 80
print(df.describe())

sort_df = df.sort_values(by = 'score', ascending=False)
print("")
print("=== Sort by score ===")
print(sort_df)

print("")
print("=== Everage age for passed ===")
print(df['age'][df['passed']].mean())


             age      score
count   3.000000   3.000000
mean   25.666667  85.000000
std     4.041452   8.888194
min    22.000000  75.000000
25%    23.500000  81.500000
50%    25.000000  88.000000
75%    27.500000  90.000000
max    30.000000  92.000000

=== Sort by score ===
    name  age  score  passed
1    Bob   30     92    True
0  Alice   25     88    True
2  Carol   22     75   False

=== Everage age for passed ===
27.5


In [ ]:
# Summary of Phase 0:
# NumPy arrays, vectorization, reshape and indexing, axis semantics,
# DataFrames, boolean filtering, derived columns, describe, sort.
# That set is genuinely the foundation the whole track builds on.